[add] bacen.py
erpbrasil/erpbrasil.base pull request #34
Opened 2023-03-15 17:08 UTC by Tiago370

2023-03-15 17:41 UTC, antoniospneto commented
Olá Tiago, nesse contexto ao que se refere esse código BACEN ? é para ser utilizado onde por exemplo ?
Desculpe minha ignorância qualquer coisa, mas é que não está claro para mim.

2023-03-15 20:51 UTC, Tiago370 commented
Olá @antoniospneto, o código BACEN é referente a issue https://github.com/erpbrasil/erpbrasil.base/issues/29.

2023-04-03 19:13 UTC, antoniospneto commented
Acho que é valido por no docstring do método, informar que esse é o "Código de País" conforme tabela do BACEN (Banco Central do Brasil) se não olhando assim fica muito genérico.

2023-04-04 18:22 UTC, antoniospneto approved these changes

2023-04-05 17:24 UTC, AndreMarcos requested changes

2023-04-05 17:24 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/bacen.py
> +# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html
Trocar a licença para MIT

2023-04-05 17:24 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/bacen.py
> +    if len(bacen) > 4 or len(bacen) <2:
Colocar zfill para padronizar os '0' a esquerda.

Exemplo:
>>> '123'.zfill(4)
'0123'

2023-04-06 12:01 UTC, mileo commented on src/erpbrasil/base/fiscal/bacen.py
> +    bacen = bacen.zfill(4)
Precisa vir antes do IF.

2023-04-14 11:28 UTC, AndreMarcos requested changes

2023-04-14 11:28 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/bacen.py
> +    coding=utf-8
Deixar a licença no formato:

Copyright (C) 2023  Tiago Amaral - KMEE
License MIT - See https://opensource.org/license/mit

Removendo o "coding=utf-8"

2023-04-14 11:28 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/bacen.py
> +    return True
Adicionar linha ao final do arquivo

2023-04-14 11:28 UTC, AndreMarcos commented on tests/test_base_fiscal_bacen.py
> +    coding=utf-8
Deixar a licença no formato:

Copyright (C) 2023 Tiago Amaral - KMEE
License MIT - See https://opensource.org/license/mit

Removendo o "coding=utf-8"

2023-04-14 11:28 UTC, AndreMarcos commented on tests/test_base_fiscal_bacen.py
> +from unittest import TestCase
Adicionar linha entre a licença e o começo das importações

2023-04-14 11:28 UTC, AndreMarcos commented on tests/test_base_fiscal_bacen.py
> +            self.assertTrue(bacen.validar(bacen_valido))
Adicionar linha ao final do arquivo

2023-04-14 12:37 UTC, rvalyi commented
Ola, depois de acertar o PR, eu diria que vc poderia tb dar um squash dos seus últimos 3 commits em um so para não bagunçar muito o histórico com iterações de dev.

2023-04-19 04:05 UTC, AndreMarcos approved these changes

2023-04-19 12:39 UTC, merged