RECOPI validation
erpbrasil/erpbrasil.base pull request #36
Opened 2023-04-04 21:04 UTC by DATVenancio

Implements the RECOPI validation as described in issue 28

2023-04-05 17:35 UTC, AndreMarcos requested changes
Tem alguns erros de sintaxe que podem ser melhorados, um próximo passo para o futuro é reativar os testes dessa biblioteca

2023-04-05 17:35 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/recopi.py
> +import datetime as dt
Adicionar licença MIT e Copyright

2023-04-15 18:36 UTC, mileo commented
Poderia dar um rebase?

2023-04-18 12:00 UTC, AndreMarcos requested changes

2023-04-18 12:00 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/recopi.py
> +    return first_verification_digit+second_verification_digit
Adicionar uma linha ao final do arquivo

2023-04-18 12:00 UTC, AndreMarcos commented on tests/test_base_fiscal_recopi_validation.py
> +        self.assertEqual(False,test_result)
Adicionar uma linha ao final do arquivo

2023-04-19 04:09 UTC, AndreMarcos requested changes

2023-04-19 04:09 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/recopi.py
> +    except:
Corrigir o uso do except
Não utilize o bare except, pois ele captura qualquer exceção.
Exemplo: except Exception

https://peps.python.org/pep-0008/#programming-recommendations

2023-04-19 04:09 UTC, AndreMarcos commented on src/erpbrasil/base/fiscal/recopi.py
> +    except:
Corrigir o uso do except
Não utilize o bare except, pois ele captura qualquer exceção.
Exemplo: except Exception

https://peps.python.org/pep-0008/#programming-recommendations

2023-05-04 17:07 UTC, closed without merging